/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Grafica;

import Casino.Casino;
import Casino.Jugada_BlackJack;
import Exceptions.ImposibleJugar;
import Exceptions.TransaccionIncorrecta;
import Juegos.BlackJackGraf.BlackJack;
import Juegos.BlackJackGraf.Carta;
import Juegos.BlackJackGraf.Jugar_BlackJack;
import Usuarios.*;
import java.awt.Color;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author alumno
 */
public class BlackJackGrafica extends javax.swing.JFrame {

    Jugar_BlackJack blacky;
    int ganador = 100;
    boolean bandera = true;
    double apuesta;
    double ganado;
    int manoP;
    int manoC;
    private Jugada_BlackJack jugada;
    JFrame root;
    Casino fipesa;
    String apu;
    User usuario;

    /**
     * Creates new form BlackJackGrafica
     */
    public BlackJackGrafica(Casino fipesa, JFrame root) {
        initComponents();
        blacky = new Jugar_BlackJack(fipesa.getUsuario());
        setLocationRelativeTo(null);
        setResizable(false);
        usuario = fipesa.getUsuario();
        this.root = root;

        //botonazo = new JButton ("mierda");
        //jPanelCrupier.add(botonazo);
        //topPanel.setBackground(new Color(0, 122, 0));
        jPanelCrupier.setBackground(new Color(0, 122, 0));
        jPanelPlayer.setBackground(new Color(0, 122, 0));
        jButtonPedirCarta.setVisible(false);

        jLabelValorC.setText(Integer.toString(blacky.getBj().contarCartas(blacky.getBj().getManoC())));
        jLabelValorP.setText(Integer.toString(blacky.getBj().contarCartas(blacky.getBj().getManoP())));
        jLabelDinero.setText(Double.toString(usuario.getMonedero().getFondos()));
        jDialogGanador.setLocationRelativeTo(null);
        jDialogPerdedor.setLocationRelativeTo(null);
        jDialogTransaccionIncorrecta.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogTransaccionIncorrecta = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        jDialogGanador = new javax.swing.JDialog();
        jLabel6 = new javax.swing.JLabel();
        jButtonContinuarJugandoG = new javax.swing.JButton();
        jButtonSalirGanador = new javax.swing.JButton();
        jLabelGanancia = new javax.swing.JLabel();
        jDialogPerdedor = new javax.swing.JDialog();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButtonContinuarJugandoP = new javax.swing.JButton();
        jButtonSalirPerdedor = new javax.swing.JButton();
        jPanelCrupier = new javax.swing.JPanel();
        jPanelPlayer = new javax.swing.JPanel();
        jTextFieldApuesta = new javax.swing.JTextField();
        jButtonPlantarse = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabelValorC = new javax.swing.JLabel();
        jLabelValorP = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonPedirCarta = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabelDinero = new javax.swing.JLabel();
        jButtonApostar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jDialogTransaccionIncorrecta.setTitle("Operacion no realizada");
        jDialogTransaccionIncorrecta.setAlwaysOnTop(true);
        jDialogTransaccionIncorrecta.setMinimumSize(new java.awt.Dimension(234, 98));
        jDialogTransaccionIncorrecta.setModal(true);
        jDialogTransaccionIncorrecta.setResizable(false);

        jLabel3.setText("<html>La operacion no se ha podido <br/>completar debido a un problema con<br/>su monedero</html>");

        javax.swing.GroupLayout jDialogTransaccionIncorrectaLayout = new javax.swing.GroupLayout(jDialogTransaccionIncorrecta.getContentPane());
        jDialogTransaccionIncorrecta.getContentPane().setLayout(jDialogTransaccionIncorrectaLayout);
        jDialogTransaccionIncorrectaLayout.setHorizontalGroup(
            jDialogTransaccionIncorrectaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogTransaccionIncorrectaLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jDialogTransaccionIncorrectaLayout.setVerticalGroup(
            jDialogTransaccionIncorrectaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogTransaccionIncorrectaLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        jDialogGanador.setAlwaysOnTop(true);
        jDialogGanador.setMinimumSize(new java.awt.Dimension(305, 172));
        jDialogGanador.setModal(true);
        jDialogGanador.setResizable(false);
        jDialogGanador.setType(java.awt.Window.Type.POPUP);

        jLabel6.setText("Has ganado la cantidad de:");

        jButtonContinuarJugandoG.setText("Continuar Jugando");
        jButtonContinuarJugandoG.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonContinuarJugandoGMouseClicked(evt);
            }
        });
        jButtonContinuarJugandoG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonContinuarJugandoGActionPerformed(evt);
            }
        });

        jButtonSalirGanador.setText("Salir");
        jButtonSalirGanador.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSalirGanadorMouseClicked(evt);
            }
        });
        jButtonSalirGanador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirGanadorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialogGanadorLayout = new javax.swing.GroupLayout(jDialogGanador.getContentPane());
        jDialogGanador.getContentPane().setLayout(jDialogGanadorLayout);
        jDialogGanadorLayout.setHorizontalGroup(
            jDialogGanadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogGanadorLayout.createSequentialGroup()
                .addGroup(jDialogGanadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jDialogGanadorLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelGanancia, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))
                    .addGroup(jDialogGanadorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonSalirGanador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonContinuarJugandoG)))
                .addGap(30, 30, 30))
        );
        jDialogGanadorLayout.setVerticalGroup(
            jDialogGanadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogGanadorLayout.createSequentialGroup()
                .addGroup(jDialogGanadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogGanadorLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogGanadorLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelGanancia, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDialogGanadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonContinuarJugandoG)
                    .addComponent(jButtonSalirGanador))
                .addGap(19, 19, 19))
        );

        jDialogPerdedor.setMinimumSize(new java.awt.Dimension(400, 300));
        jDialogPerdedor.setModal(true);

        jLabel7.setText("Gana la banca!!!!");

        jLabel8.setText("SORRY  ; )");

        jButtonContinuarJugandoP.setText("Continuar Jugando");
        jButtonContinuarJugandoP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonContinuarJugandoPMouseClicked(evt);
            }
        });
        jButtonContinuarJugandoP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonContinuarJugandoPActionPerformed(evt);
            }
        });

        jButtonSalirPerdedor.setText("Salir");
        jButtonSalirPerdedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSalirPerdedorMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jDialogPerdedorLayout = new javax.swing.GroupLayout(jDialogPerdedor.getContentPane());
        jDialogPerdedor.getContentPane().setLayout(jDialogPerdedorLayout);
        jDialogPerdedorLayout.setHorizontalGroup(
            jDialogPerdedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogPerdedorLayout.createSequentialGroup()
                .addGroup(jDialogPerdedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialogPerdedorLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel8))
                    .addGroup(jDialogPerdedorLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jDialogPerdedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonSalirPerdedor)
                            .addComponent(jLabel7))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialogPerdedorLayout.createSequentialGroup()
                .addGap(0, 212, Short.MAX_VALUE)
                .addComponent(jButtonContinuarJugandoP)
                .addGap(65, 65, 65))
        );
        jDialogPerdedorLayout.setVerticalGroup(
            jDialogPerdedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialogPerdedorLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jLabel7)
                .addGap(43, 43, 43)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonContinuarJugandoP)
                .addGap(18, 18, 18)
                .addComponent(jButtonSalirPerdedor)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BlackJack");
        setBackground(new java.awt.Color(0, 153, 0));
        setForeground(java.awt.Color.green);

        jPanelCrupier.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Mano Crupier", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Wide Latin", 1, 14))); // NOI18N
        jPanelCrupier.setPreferredSize(new java.awt.Dimension(804, 170));
        jPanelCrupier.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelPlayer.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Mano Jugador", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Wide Latin", 1, 14))); // NOI18N
        jPanelPlayer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldApuesta.setFont(new java.awt.Font("Wide Latin", 1, 12)); // NOI18N
        jTextFieldApuesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldApuestaActionPerformed(evt);
            }
        });

        jButtonPlantarse.setFont(new java.awt.Font("Wide Latin", 1, 12)); // NOI18N
        jButtonPlantarse.setText("Plantarse");
        jButtonPlantarse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonPlantarseMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Wide Latin", 1, 12)); // NOI18N
        jLabel1.setText("Su mano vale:");

        jLabelValorC.setFont(new java.awt.Font("Wide Latin", 1, 18)); // NOI18N

        jLabelValorP.setFont(new java.awt.Font("Wide Latin", 1, 18)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Wide Latin", 1, 12)); // NOI18N
        jLabel4.setText("Tu mano vale:");

        jLabel2.setText("Introduce tu apuesta aqui:");

        jButtonPedirCarta.setText("Pedir carta");
        jButtonPedirCarta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonPedirCartaMouseClicked(evt);
            }
        });
        jButtonPedirCarta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPedirCartaActionPerformed(evt);
            }
        });

        jButton1.setText("Limpiar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jLabel5.setText("Tienes:");

        jLabelDinero.setFont(new java.awt.Font("Arial Black", 0, 24)); // NOI18N

        jButtonApostar.setText("Apostar");
        jButtonApostar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonApostarMouseClicked(evt);
            }
        });

        jButton2.setText("Volver");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jLabelValorC, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelCrupier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(12, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(114, 114, 114)
                                .addComponent(jButtonPedirCarta)
                                .addGap(142, 142, 142)
                                .addComponent(jButtonPlantarse, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanelPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 804, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel4)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jButtonApostar)
                                        .addComponent(jLabelDinero, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton2))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jTextFieldApuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabelValorP, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(35, 35, 35)))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelValorC, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(12, Short.MAX_VALUE)
                        .addComponent(jPanelCrupier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelValorP, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonPlantarse, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonPedirCarta)
                        .addGap(22, 22, 22)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldApuesta, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jButtonApostar)
                                .addGap(36, 36, 36)
                                .addComponent(jLabelDinero, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jButton2)))
                .addContainerGap(92, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Reparte cartas al jugador y actualiza la GUI
     */
    private void repartirCartasP() {
        this.blacky.getBj().pedirCartaPlayer();

        jPanelPlayer.removeAll();
        jPanelPlayer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        ArrayList<Carta> mano = this.blacky.getBj().getManoP();
        Carta carta;
        int pos = 30;
        for (int i = 0; i < mano.size(); i++) {

            carta = mano.get(i);
            carta.setToolTipText(carta.getSimbolo() + "  de " + carta.getTipo());
            carta.setIcon(carta.getImagen());
            carta.setBorderPainted(false);
            carta.setBackground(null);
            carta.setMargin(new java.awt.Insets(0, 0, 0, 0));
            carta.setRolloverEnabled(false);
            jPanelPlayer.add(carta, new org.netbeans.lib.awtextra.AbsoluteConstraints(pos, 23, 100, 130));
            pos += 120;
        }

        jPanelPlayer.updateUI();

    }

    /**
     * Reparte cartas al crupier y actualiza la GUI
     */
    private void repartirCartasC() {

        this.blacky.getBj().pedirCartaCrupier();
        jPanelCrupier.removeAll();
        jPanelCrupier.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        ArrayList<Carta> mano = this.blacky.getBj().getManoC();
        Carta carta;
        int pos = 30;
        for (int i = 0; i < mano.size(); i++) {

            carta = mano.get(i);
            carta.setToolTipText(carta.getSimbolo() + "  de " + carta.getTipo());
            carta.setIcon(carta.getImagen());
            carta.setBorderPainted(false);
            carta.setBackground(null);
            carta.setMargin(new java.awt.Insets(0, 0, 0, 0));
            carta.setRolloverEnabled(false);
            carta.setToolTipText(carta.getSimbolo() + "  de " + carta.getTipo());
            jPanelCrupier.add(carta, new org.netbeans.lib.awtextra.AbsoluteConstraints(pos, 23, 100, 130));
            pos += 90;
        }

        jPanelCrupier.updateUI();

    }

    /**
     * La logica que sigue el crupier cuando se hace juego. Si tiene menos de 17
     * pide carta, sino no. Realiza la operacion de añadir fondos en el monedero
     * si el ganador es el jugador.
     */
    public void logicaCrupier() throws ImposibleJugar {
        while (blacky.pedirCartasC()){
            repartirCartasC();
            actualizarValorC();
        }
        ganador = blacky.logicaCrupier();
        try {
            blacky.ganador(ganador);
            if (ganador !=0){
                jLabelGanancia.setText(apu);
                jDialogGanador.setVisible(true);               
            } else {
                jDialogPerdedor.setVisible(true);
            }
        } catch (TransaccionIncorrecta ex) {
            throw new ImposibleJugar("No se ha podido realizar la operacion");
        }

        /*apuesta = Double.parseDouble(this.jTextFieldApuesta.getText());
            apu = Double.toString(apuesta * ganador / 100);
            boolean banderaC = true;
            boolean hecho = true;
            
            while (banderaC) {
            //SE COMPRUEBA QUE LA MANO DEL CRUPIER NO SE PASA DE 21
            if (blacky.getBj().comprobar21(blacky.getBj().getManoC()) == 0) {
            ganador = 100;
            banderaC = false;
            jLabelGanancia.setText(apu);
            apu = "";
            jDialogGanador.setVisible(true);
            hecho = false;
            
            //SI TIENE 17 O MENOS PIDE CARTA
            } else if (blacky.getBj().contarCartas(blacky.getBj().getManoC()) < 17) {
            repartirCartasC();
            
            } else {
            banderaC = false;
            }
            actualizarValorC();
            }
            
            //LOGICA PARA ASIGNAR EL GANADOR
            /* if (blacky.getBj().comprobar21(blacky.getBj().getManoC()) == 1 && blacky.getBj().comprobar21(blacky.getBj().getManoP()) == 0) {
            ganador = 0;
            } else if (blacky.getBj().contarCartas(blacky.getBj().getManoP()) <= 21 && blacky.getBj().contarCartas(blacky.getBj().getManoC()) < blacky.getBj().contarCartas(blacky.getBj().getManoP()) && blacky.getBj().getManoP().size() > 2) {
            ganador = 100;
            } else if (blacky.getBj().contarCartas(blacky.getBj().getManoC()) <= 21 && blacky.getBj().contarCartas(blacky.getBj().getManoP()) < blacky.getBj().contarCartas(blacky.getBj().getManoC())) {
            ganador = 0;
            }*/
        //SI EL GANADOR ES EL USUARIO
        /*if (hecho) {
            
            if (blacky.getBj().contarCartas(blacky.getBj().getManoP()) <= 21 && blacky.getBj().contarCartas(blacky.getBj().getManoC()) < blacky.getBj().contarCartas(blacky.getBj().getManoP()) && blacky.getBj().getManoP().size() > 2) {
            
            ganador = 100;
            
            jLabelGanancia.setText(apu);
            jDialogGanador.setVisible(true);
            apu = "";
            
            try {
            usuario.añadirFondos(apuesta);
            usuario.añadirFondos(apuesta * ganador / 100);
            actualizarValorD();
            apuesta = 0;
            } catch (TransaccionIncorrecta ex) {
            jDialogTransaccionIncorrecta.setVisible(true);
            }
            } else if (blacky.getBj().comprobar21(blacky.getBj().getManoC()) == 1 && blacky.getBj().comprobar21(blacky.getBj().getManoP()) == 0) {
            jDialogPerdedor.setVisible(true);
            } else if (blacky.getBj().contarCartas(blacky.getBj().getManoC()) <= 21 && blacky.getBj().contarCartas(blacky.getBj().getManoP()) < blacky.getBj().contarCartas(blacky.getBj().getManoC())) {
            jDialogPerdedor.setVisible(true);
            } else if (blacky.getBj().contarCartas(blacky.getBj().getManoP()) == blacky.getBj().contarCartas(blacky.getBj().getManoC())) {
            ganador = 0;
            jLabelGanancia.setText(apu);
            jDialogGanador.setVisible(true);
            apu = "";
            
            try {
            
            usuario.añadirFondos(apuesta);
            actualizarValorD();
            apuesta = 0;
            } catch (TransaccionIncorrecta ex) {
            jDialogTransaccionIncorrecta.setVisible(true);
            }
            
            } else {
            jDialogPerdedor.setVisible(true);
            }
            }*/
    }

    /**
     * Crea una jugada con los datos en memoria
     *
     * @return la jugada en si
     */
    public Jugada_BlackJack setJugada() {

        manoP = blacky.getBj().contarCartas(blacky.getBj().getManoP());
        manoC = blacky.getBj().contarCartas(blacky.getBj().getManoC());
        jugada = new Jugada_BlackJack(apuesta, ganado, manoP, manoC);
        return getJugada();

    }

    /**
     * Crea una conexion a la base de datos y guarda la jugada directamente en
     * la base de datos.
     */
    public void guardarJugada() {
        jugada.guardar(usuario.getUsername());
    }

    public void actualizarValorP() {
        jLabelValorP.setText(Integer.toString(this.blacky.getBj().contarCartas(this.blacky.getBj().getManoP())));
    }

    public void actualizarValorC() {
        jLabelValorC.setText(Integer.toString(this.blacky.getBj().contarCartas(this.blacky.getBj().getManoC())));
    }

    public void actualizarValorD() {
        jLabelDinero.setText(Double.toString(usuario.getMonedero().getFondos()));
    }


    private void jTextFieldApuestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldApuestaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldApuestaActionPerformed

    private void jButtonPedirCartaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonPedirCartaMouseClicked

        apuesta = Double.parseDouble(this.jTextFieldApuesta.getText());
        apu = Double.toString(apuesta * ganador / 100);

        repartirCartasP();
        actualizarValorC();
        actualizarValorP();
        if (blacky.getBj().comprobar21(blacky.getBj().getManoP()) == 1) {
            ganador = 100;
            apu = Double.toString(apuesta * ganador / 100);
            jLabelGanancia.setText(apu);
            jButtonPedirCarta.setVisible(false);
            jButtonPlantarse.setVisible(false);
            jDialogGanador.setVisible(true);

            try {
                usuario.añadirFondos(apuesta * ganador / 100);
                usuario.añadirFondos(apuesta);
                actualizarValorD();
                apuesta = 0;
                apu = "";
                guardarJugada();
            } catch (TransaccionIncorrecta ex) {
                jDialogTransaccionIncorrecta.setVisible(true);
            }

        } else if (blacky.getBj().comprobar21(blacky.getBj().getManoP()) == 0) {
            jButtonPedirCarta.setVisible(false);
            jButtonPlantarse.setVisible(false);
            jDialogPerdedor.setVisible(true);

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPedirCartaMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        jPanelPlayer.removeAll();
        jPanelPlayer.updateUI();   // TODO add your handling code here:
        jDialogGanador.setLocationRelativeTo(null);
        jDialogGanador.setVisible(true);
        jDialogGanador.setTitle("hola?=");
        jDialogTransaccionIncorrecta.setVisible(true);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButtonApostarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonApostarMouseClicked

        //jTextFieldApuesta.setEditable(false);
        jTextFieldApuesta.setEnabled(false);
        apuesta = Double.parseDouble(this.jTextFieldApuesta.getText());
        apu = Double.toString(apuesta * ganador / 100);
        blacky.setApu(apuesta);

        try {
            usuario.retirarFondos(apuesta);
            jButtonApostar.setVisible(false);
            this.repartirCartasP();
            this.repartirCartasC();
            this.repartirCartasP();
            actualizarValorC();
            actualizarValorP();
            actualizarValorD();
            if (blacky.getBj().comprobar21(blacky.getBj().getManoP()) == 1) {

                ganador = 150;
                apu = Double.toString(apuesta * ganador / 100);
                jLabelGanancia.setText(apu);
                jDialogGanador.setVisible(true);

                try {
                    fipesa.getUsuario().añadirFondos(apuesta * ganador / 100);
                    fipesa.getUsuario().añadirFondos(apuesta);
                    guardarJugada();

                } catch (TransaccionIncorrecta ex) {
                    jDialogTransaccionIncorrecta.setVisible(true);
                }
                apuesta = 0;
                actualizarValorD();
                apu = "";

            }

            jButtonPedirCarta.setVisible(true);

        } catch (TransaccionIncorrecta ex) {
            jDialogTransaccionIncorrecta.setVisible(true);
            jTextFieldApuesta.setEnabled(true);
            apuesta = 0;
            jTextFieldApuesta.setText("");
            jButtonApostar.setVisible(true);

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonApostarMouseClicked

    private void jButtonPedirCartaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPedirCartaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonPedirCartaActionPerformed

    private void jButtonPlantarseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonPlantarseMouseClicked
        try {
            logicaCrupier();
        } catch (ImposibleJugar ex) {
            JOptionPane.showMessageDialog(rootPane, "Transaccion Incorrecta", "CUIDADO!!", JOptionPane.ERROR_MESSAGE);
        }
        actualizarValorC();
        actualizarValorP();
        actualizarValorD();
    }//GEN-LAST:event_jButtonPlantarseMouseClicked

    private void jButtonSalirGanadorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSalirGanadorMouseClicked
        bandera = false;
        jButtonApostar.setVisible(true);
        System.exit(0);// TODO add your handling code here:
    }//GEN-LAST:event_jButtonSalirGanadorMouseClicked

    private void jButtonContinuarJugandoGMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonContinuarJugandoGMouseClicked

    }//GEN-LAST:event_jButtonContinuarJugandoGMouseClicked

    private void jButtonContinuarJugandoGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonContinuarJugandoGActionPerformed
        blacky.getBj().getManoP().clear();
        blacky.getBj().getManoC().clear();
        jDialogGanador.setVisible(false);// TODO add your handling code here:
        blacky.getBj().getManoP().clear();
        blacky.getBj().getManoC().clear();
        actualizarValorC();
        actualizarValorD();
        actualizarValorP();
        jPanelCrupier.removeAll();
        jPanelPlayer.removeAll();
        jPanelCrupier.updateUI();
        jPanelPlayer.updateUI();
        jButtonPlantarse.setVisible(true);
        jButtonApostar.setVisible(true);
        jTextFieldApuesta.setEnabled(true);
        jTextFieldApuesta.setEditable(true);
        jTextFieldApuesta.setText("");
    }//GEN-LAST:event_jButtonContinuarJugandoGActionPerformed

    private void jButtonContinuarJugandoPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonContinuarJugandoPMouseClicked
        blacky.getBj().getManoP().clear();
        blacky.getBj().getManoC().clear();
        jDialogPerdedor.setVisible(false);// TODO add your handling code here:
        actualizarValorC();
        actualizarValorD();
        actualizarValorP();
        jPanelCrupier.removeAll();
        jPanelPlayer.removeAll();
        jPanelCrupier.updateUI();
        jPanelPlayer.updateUI();
        jButtonPlantarse.setVisible(true);
        jButtonApostar.setVisible(true);
        jTextFieldApuesta.setEnabled(true);
        jTextFieldApuesta.setEditable(true);
        jTextFieldApuesta.setText("");
    }//GEN-LAST:event_jButtonContinuarJugandoPMouseClicked

    private void jButtonContinuarJugandoPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonContinuarJugandoPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonContinuarJugandoPActionPerformed

    private void jButtonSalirPerdedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSalirPerdedorMouseClicked
        bandera = false;
        System.exit(0); // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSalirPerdedorMouseClicked

    private void jButtonSalirGanadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirGanadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSalirGanadorActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
        root.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    public JTextField getjTextFieldApuesta() {
        return jTextFieldApuesta;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BlackJackGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BlackJackGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BlackJackGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BlackJackGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        BlackJack bj = new BlackJack();
        User usuario = new P2W("a", "a", "a", "a", "a", "a", 2);
        try {
            usuario.añadirFondos(4000);
        } catch (TransaccionIncorrecta ex) {
            Logger.getLogger(BlackJackGrafica.class.getName()).log(Level.SEVERE, null, ex);
        }


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BlackJackGrafica(null, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonApostar;
    private javax.swing.JButton jButtonContinuarJugandoG;
    private javax.swing.JButton jButtonContinuarJugandoP;
    private javax.swing.JButton jButtonPedirCarta;
    private javax.swing.JButton jButtonPlantarse;
    private javax.swing.JButton jButtonSalirGanador;
    private javax.swing.JButton jButtonSalirPerdedor;
    private javax.swing.JDialog jDialogGanador;
    private javax.swing.JDialog jDialogPerdedor;
    private javax.swing.JDialog jDialogTransaccionIncorrecta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelDinero;
    private javax.swing.JLabel jLabelGanancia;
    private javax.swing.JLabel jLabelValorC;
    private javax.swing.JLabel jLabelValorP;
    private javax.swing.JPanel jPanelCrupier;
    private javax.swing.JPanel jPanelPlayer;
    private javax.swing.JTextField jTextFieldApuesta;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the jButton1C
     */
    /**
     * @return the jButtonPedir
     */
    /**
     * @return the jButtonPlantarse
     */
    public javax.swing.JButton getjButtonPlantarse() {
        return jButtonPlantarse;
    }

    /**
     * @return the jLabelValorC
     */
    public javax.swing.JLabel getjLabelValorC() {
        return jLabelValorC;
    }

    /**
     * @return the jLabelValorP
     */
    public javax.swing.JLabel getjLabelValorP() {
        return jLabelValorP;
    }

    /**
     * @return the jDialogTransaccionIncorrecta
     */
    public javax.swing.JDialog getjDialogTransaccionIncorrecta() {
        return jDialogTransaccionIncorrecta;
    }

    /**
     * @return the jugada
     */
    public Jugada_BlackJack getJugada() {
        return jugada;
    }
}
