/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Grafica;

import Casino.Casino;
import Exceptions.PremiumUpdateException;
import Exceptions.TransaccionIncorrecta;
import Juegos.BlackJackGraf.JugarBlackJack;
import Usuarios.F2P;
import Usuarios.*;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author alumno
 */
public class JuegosGrafica extends javax.swing.JFrame {

    
    private Casino fipesa;
    private JFrame root;
    private ImageIcon f2p = new ImageIcon(getClass().getResource("/resources/imagenesusers/f2pedit.png"));
    private ImageIcon p2w = new ImageIcon(getClass().getResource("/resources/imagenesusers/p2wedit.png"));
    private ImageIcon p2wss = new ImageIcon(getClass().getResource("/resources/imagenesusers/p2wssedit.png"));
    
    
    public JuegosGrafica(Casino fipesa,JFrame root) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.fipesa = fipesa;
        this.root = root;
        jTextField1.setText(fipesa.getUsuario().getUsername());
        jTextField2.setText(Double.toString(fipesa.getUsuario().getMonedero().getFondos()));
        if(fipesa.getUsuario() instanceof P2WSS){
            jLabel5.setIcon(p2wss);
        }else if(fipesa.getUsuario() instanceof P2W){
            jLabel5.setIcon(p2w);
        }else if(fipesa.getUsuario() instanceof F2P){
            jLabel5.setIcon(f2p);
            jButton2.setEnabled(false);
            jButton3.setEnabled(false);
            jButton4.setEnabled(false);
        }
        
    }
    
    @Override
    public void setVisible(boolean a){
        super.setVisible(a);
        jTextField2.setText(Double.toString(fipesa.getUsuario().getMonedero().getFondos()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jBrul = new javax.swing.JButton();
        jBBj = new javax.swing.JButton();
        jBSlots = new javax.swing.JButton();
        jBatras = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 600));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Matura MT Script Capitals", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 0));
        jLabel2.setText("Seleccione un juego: ");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(230, 50, 370, 40);

        jBrul.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBrul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBrulActionPerformed(evt);
            }
        });
        jPanel1.add(jBrul);
        jBrul.setBounds(570, 270, 80, 80);

        jBBj.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Imagenes/black.png"))); // NOI18N
        jBBj.setBorder(null);
        jBBj.setContentAreaFilled(false);
        jBBj.setFocusPainted(false);
        jBBj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBjActionPerformed(evt);
            }
        });
        jPanel1.add(jBBj);
        jBBj.setBounds(300, 190, 160, 159);

        jBSlots.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Imagenes/slots.png"))); // NOI18N
        jBSlots.setText("SLOTS");
        jBSlots.setBorder(null);
        jBSlots.setBorderPainted(false);
        jBSlots.setContentAreaFilled(false);
        jBSlots.setFocusPainted(false);
        jBSlots.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSlotsActionPerformed(evt);
            }
        });
        jPanel1.add(jBSlots);
        jBSlots.setBounds(90, 280, 140, 170);

        jBatras.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jBatras.setText("Salir");
        jBatras.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jBatras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBatrasActionPerformed(evt);
            }
        });
        jPanel1.add(jBatras);
        jBatras.setBounds(20, 520, 80, 60);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255, 200));

        jLabel5.setText("jLabel4");

        jLabel6.setText("Jugando como: ");

        jTextField1.setText("jTextField1");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel7.setText("Fondos: ");

        jTextField2.setText("jTextField2");

        jButton2.setText("Monedero");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Logout");
        jButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Premium");
        jButton4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addGap(41, 41, 41)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                            .addComponent(jTextField2)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton3)
                            .addComponent(jButton4))
                        .addGap(0, 17, Short.MAX_VALUE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(440, 400, 354, 120);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Imagenes/fondoSelJuego.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBrulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBrulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBrulActionPerformed

    private void jBatrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBatrasActionPerformed
       
        System.exit(0);
        
    }//GEN-LAST:event_jBatrasActionPerformed

    private void jBBjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBjActionPerformed
        BlackJackGrafica blacky = new BlackJackGrafica(fipesa,this);      
        blacky.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jBBjActionPerformed

    private void jBSlotsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSlotsActionPerformed

        SlotsGrafica slots = new SlotsGrafica(fipesa,this);
        slots.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_jBSlotsActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if(fipesa.getUsuario() instanceof F2P){
            jButton3.setEnabled(false);
        } else{
            fipesa.logout();
            this.setVisible(false);
            root.setVisible(true);
        }        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        VerMonedero vm = new VerMonedero(fipesa,this);
        vm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       
        if(fipesa.getUsuario()instanceof P2W){
            UserUpgrade uu = new UserUpgrade(this,true);
            uu.setVisible(true);

            if(uu.isValido()){
                try {
                    P2W p2w = (P2W)fipesa.getUsuario();
                    fipesa.setUsuario(p2w.UpgradeSubscription(uu.getDias()));
                    JuegosGrafica jg = new JuegosGrafica(fipesa, this);
                jg.setVisible(true);
                    this.setVisible(false);
                } catch (PremiumUpdateException ex) {
                    JOptionPane.showMessageDialog(rootPane, "Fallo en la actualizacion","AVISO" , JOptionPane.ERROR_MESSAGE);
                } catch (TransaccionIncorrecta ex) {
                    JOptionPane.showMessageDialog(rootPane, "Usted no dispone de fondos suficientes","ERROR" , JOptionPane.ERROR_MESSAGE);
                }
            }   
        }else if(fipesa.getUsuario() instanceof P2WSS){
            UserUpgrade uu = new UserUpgrade(this,true);
            uu.setVisible(true);

            if(uu.isValido()){
                try {
                    P2WSS p2wss = (P2WSS)fipesa.getUsuario();
                    fipesa.setUsuario(p2wss.UpgradeSubscription(uu.getDias()));
                    JuegosGrafica jg = new JuegosGrafica(fipesa, this);
                    jg.setVisible(true);
                    this.setVisible(false);
                } catch (PremiumUpdateException ex) {
                    JOptionPane.showMessageDialog(rootPane, "Fallo en la actualizacion","AVISO" , JOptionPane.ERROR_MESSAGE);
                } catch (TransaccionIncorrecta ex) {
                    JOptionPane.showMessageDialog(rootPane, "Usted no dispone de fondos suficientes","ERROR" , JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JuegosGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JuegosGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JuegosGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JuegosGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JuegosGrafica(null,null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBBj;
    private javax.swing.JButton jBSlots;
    private javax.swing.JButton jBatras;
    private javax.swing.JButton jBrul;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
