/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Grafica;

import Casino.Casino;
import Juegos.BlackJackGraf.JugarBlackJack;
import Usuarios.User;
import javax.swing.JFrame;

/**
 *
 * @author alumno
 */
public class JuegosGrafica extends javax.swing.JFrame {

    
    private Casino fipesa;
    private JFrame root;
    
    
    public JuegosGrafica(Casino fipesa,JFrame root) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        this.fipesa = fipesa;
        this.root = root;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jBrul = new javax.swing.JButton();
        jBBj = new javax.swing.JButton();
        jBSlots = new javax.swing.JButton();
        jBatras = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\alumno\\Desktop\\juegos-casinos_logo (1).jpg")); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(550, 10, 327, 120);

        jLabel2.setFont(new java.awt.Font("Matura MT Script Capitals", 1, 36)); // NOI18N
        jLabel2.setText("Seleccione un juego: ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(550, 140, 367, 49);

        jBrul.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jBrul.setIcon(new javax.swing.ImageIcon("C:\\Users\\alumno\\Desktop\\89.jpg")); // NOI18N
        jBrul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBrulActionPerformed(evt);
            }
        });
        getContentPane().add(jBrul);
        jBrul.setBounds(510, 240, 440, 300);

        jBBj.setIcon(new javax.swing.ImageIcon("C:\\Users\\alumno\\Desktop\\BLACK.png")); // NOI18N
        jBBj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBBjActionPerformed(evt);
            }
        });
        getContentPane().add(jBBj);
        jBBj.setBounds(1030, 240, 290, 300);

        jBSlots.setIcon(new javax.swing.ImageIcon("C:\\Users\\alumno\\Desktop\\51GgLQx6dML._SY355_.jpg")); // NOI18N
        jBSlots.setText("SLOTS");
        jBSlots.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSlotsActionPerformed(evt);
            }
        });
        getContentPane().add(jBSlots);
        jBSlots.setBounds(120, 180, 310, 380);

        jBatras.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jBatras.setText("Atrás");
        jBatras.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jBatras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBatrasActionPerformed(evt);
            }
        });
        getContentPane().add(jBatras);
        jBatras.setBounds(500, 650, 100, 70);

        jButton1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setText("Cerrar Sesión");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 4, true));
        getContentPane().add(jButton1);
        jButton1.setBounds(790, 650, 170, 70);

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\alumno\\Desktop\\fondo-general.jpg")); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(-10, -20, 1500, 860);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBrulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBrulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBrulActionPerformed

    private void jBatrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBatrasActionPerformed
       
        this.setVisible(false);
        root.setVisible(true);       
        
    }//GEN-LAST:event_jBatrasActionPerformed

    private void jBBjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBBjActionPerformed
        BlackJackGrafica blacky = new BlackJackGrafica(fipesa.getUsuario());      
        blacky.setVisible(true);
    }//GEN-LAST:event_jBBjActionPerformed

    private void jBSlotsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSlotsActionPerformed

        SlotsGrafica slots = new SlotsGrafica(fipesa,this);
        slots.setVisible(true);
        this.setVisible(false);

    }//GEN-LAST:event_jBSlotsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JuegosGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JuegosGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JuegosGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JuegosGrafica.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JuegosGrafica(null,null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBBj;
    private javax.swing.JButton jBSlots;
    private javax.swing.JButton jBatras;
    private javax.swing.JButton jBrul;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
