/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Grafica;

import Juegos.BlackJackGraf.Carta;
import java.awt.Color;
import java.awt.Container;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author mazhe
 */
public class PruebaEdgar extends javax.swing.JFrame {
    JButton boton1 ;
    ArrayList<Carta> baraja; 
    JLabel texto ;
    /**
     * Creates new form PruebaEdgar
     */
    public PruebaEdgar() {
        super ("PRUEBA  !!");
        //setVisible(true);
       
        
        //getContentPane().setLayout(layout);
        
        
        initComponents();
        
        setLocationRelativeTo(null);
        
       

        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPrueba = new javax.swing.JPanel();
        jPanelCrupier = new javax.swing.JPanel();
        jPanelMano = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelPrueba.setLayout(new java.awt.GridLayout(2, 1));

        jPanelCrupier.setBorder(javax.swing.BorderFactory.createTitledBorder("Mano Crupier"));
        jPanelCrupier.setLayout(new java.awt.GridLayout(1, 5));
        jPanelPrueba.add(jPanelCrupier);

        jPanelMano.setBorder(javax.swing.BorderFactory.createTitledBorder("Tu mano"));
        jPanelMano.setLayout(new java.awt.GridLayout(1, 5));
        jPanelPrueba.add(jPanelMano);

        jButton1.setText("Repartir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Salir");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelPrueba, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 299, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(74, 74, 74))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelPrueba, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    repartir ();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    
    public void repartir (){
        jPanelCrupier.removeAll();
        jPanelCrupier.setLayout(new java.awt.GridLayout(1, 5));
         baraja = Carta.crearBaraja();
         Carta carta;
        for (int i = 0; i < 5 ; i++){
            carta = baraja.get(i);
            carta.setText(carta.getSimbolo() + "  de " + carta.getTipo());
            carta.setIcon(carta.getImagen());
            jPanelCrupier.add(carta);
            
        }
        jPanelCrupier.updateUI();
        jPanelMano.add(baraja.get(29));
        jPanelMano.updateUI();
       
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PruebaEdgar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PruebaEdgar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PruebaEdgar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PruebaEdgar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PruebaEdgar().setVisible(true);
            }
            
        });
        Carta.crearBaraja();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanelCrupier;
    private javax.swing.JPanel jPanelMano;
    private javax.swing.JPanel jPanelPrueba;
    // End of variables declaration//GEN-END:variables
}
