/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Juegos.BlackJackGraf;

import java.util.ArrayList;

/**
 *
 * @author mazhe
 */
public class baraja extends javax.swing.JFrame {

    /**
     * Creates new form baraja
     */
    public baraja() {
        super ("Prueba Baraja.");
        initComponents();
        this.setSize(this.getToolkit().getScreenSize());
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jPanelBaraja = new javax.swing.JPanel();
        jButtonRepartir = new javax.swing.JButton();
        jButtonLimpiar = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelBaraja.setLayout(new java.awt.GridLayout(4, 13));

        jButtonRepartir.setText("Repartir");
        jButtonRepartir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonRepartirMouseClicked(evt);
            }
        });
        jButtonRepartir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRepartirActionPerformed(evt);
            }
        });

        jButtonLimpiar.setText("Limpiar");
        jButtonLimpiar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonLimpiarMouseClicked(evt);
            }
        });

        jButtonSalir.setText("Salir");
        jButtonSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSalirMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBaraja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jButtonRepartir)
                .addGap(162, 162, 162)
                .addComponent(jButtonLimpiar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 183, Short.MAX_VALUE)
                .addComponent(jButtonSalir)
                .addGap(92, 92, 92))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelBaraja, javax.swing.GroupLayout.PREFERRED_SIZE, 572, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonRepartir)
                    .addComponent(jButtonLimpiar)
                    .addComponent(jButtonSalir))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonRepartirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRepartirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRepartirActionPerformed

    private void jButtonSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSalirMouseClicked
    System.exit(0);
    // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSalirMouseClicked

    private void jButtonRepartirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRepartirMouseClicked
    repartirCartas();    // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRepartirMouseClicked

    private void jButtonLimpiarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonLimpiarMouseClicked
    borrar();    // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLimpiarMouseClicked

       
    private void repartirCartas (){
        ArrayList <Carta> baraja = Carta.crearBaraja();
         jPanelBaraja.removeAll();
        jPanelBaraja.setLayout(new java.awt.GridLayout(4, 13));
         baraja = Carta.crearBaraja();
         Carta carta;
        for (int i = 0; i < baraja.size() ; i++){
            carta = baraja.get(i);
            carta.setText(carta.getSimbolo() + "  de " + carta.getTipo());
            carta.setIcon(carta.getImagen());
            jPanelBaraja.add(carta);
            
        }
        
        jPanelBaraja.updateUI();
        
       
    }
    private void borrar (){
        jPanelBaraja.removeAll();
        jPanelBaraja.updateUI();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(baraja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(baraja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(baraja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(baraja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new baraja().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonLimpiar;
    private javax.swing.JButton jButtonRepartir;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JPanel jPanelBaraja;
    // End of variables declaration//GEN-END:variables
}
